# The URL the site will be built for
base_url = "https://henryn.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true




# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

[extra]
# Put all your custom variables here

